version: "3.9"

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
  
networks:
  app-network:
    driver: bridge